apiVersion: v1
kind: Service
metadata:
  name: hdfs-secondary-namenode
  labels:
    app: chp
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}

spec:
  ClusterIP: none
  ports:
    - port: 50070
      name: hdfs-secondary-namenode
  selector:
    app: chp
    release: {{ .Release.Name }}
